services:
  snipeit_db:
    container_name: snipeit_db
    image: mariadb:11.4.7
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${SNIPEIT_DB_NAME}
      MYSQL_USER: ${SNIPEIT_DB_USER}
      MYSQL_PASSWORD: ${SNIPEIT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SNIPEIT_DB_ROOT_PASSWORD}
      TZ: ${SNIPEIT_DB_TZ}
    volumes:
      - "${SNIPEIT_DB_BASE_PATH}/mysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=${SNIPEIT_WATCHTOWER_LABEL_ENABLE}"
    networks:
      - snipeit_network

  snipeit:
    container_name: snipeit
    image: snipe/snipe-it:${SNIPEIT_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      snipeit_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${SNIPEIT_PORT}:80"
    environment:
      APP_URL: ${SNIPEIT_APP_URL}
      APP_ENV: ${SNIPEIT_APP_ENV}
      APP_DEBUG: ${SNIPEIT_APP_DEBUG}
      APP_KEY: ${SNIPEIT_APP_KEY}
      DB_CONNECTION: ${SNIPEIT_DB_CONNECTION}
      DB_HOST: ${SNIPEIT_DB_HOST}
      DB_DATABASE: ${SNIPEIT_DB_NAME}
      DB_USERNAME: ${SNIPEIT_DB_USER}
      DB_PASSWORD: ${SNIPEIT_DB_PASSWORD}
      DB_PORT: 3306
      TZ: ${SNIPEIT_TZ}
    volumes:
      - "${SNIPEIT_BASE_PATH}/uploads:/var/lib/snipeit"
    labels:
      - "com.centurylinklabs.watchtower.enable=${SNIPEIT_WATCHTOWER_LABEL_ENABLE}"
    networks:
      - snipeit_network

networks:
  snipeit_network:
    name: snipeit_network
    driver: bridge

