services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - .env
    ports:
      - "53:53/tcp" # dns
      - "53:53/udp" # dns
      - "5005:80/tcp" # interface web
      - "123:123/udp" # NTP server
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: ${WEBPASSWORD}
      FTLCONF_webserver_api_password: ${WEBSERVER_API_PASSWORD} 
      FTLCONF_dns_listeningMode: 'ALL' # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
    volumes:
      - '/home/pi-hole/etc:/etc/pihole/'
      - '/home/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - SYS_TIME # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
    restart: unless-stopped
    networks:
      - pihole_network

networks:
  pihole_network:
    name: pihole_network
    driver: bridge