version: "3.8"

services:
  zabbix_db:
    image: postgres:${ZABBIX_DB_VERSION}
    container_name: zabbix_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${ZABBIX_DB_USER}
      - POSTGRES_PASSWORD=${ZABBIX_DB_PASSWORD}
      - POSTGRES_DB=${ZABBIX_DB_NAME}
    volumes:
      - ${ZABBIX_BASE_PATH}/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ZABBIX_DB_USER} -d ${ZABBIX_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - zabbix_network

  zabbix_server:
    image: zabbix/zabbix-server-pgsql:${ZABBIX_VERSION}
    container_name: zabbix_server
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_USER=${ZABBIX_DB_USER}
      - POSTGRES_PASSWORD=${ZABBIX_DB_PASSWORD}
      - POSTGRES_DB=${ZABBIX_DB_NAME}
      - TZ=${TZ}
    depends_on:
      zabbix_db:
        condition: service_healthy
    networks:
      - zabbix_network
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_LABEL_ENABLE}"

  zabbix_web:
    image: zabbix/zabbix-web-nginx-pgsql:${ZABBIX_VERSION}
    container_name: zabbix_web
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_USER=${ZABBIX_DB_USER}
      - POSTGRES_PASSWORD=${ZABBIX_DB_PASSWORD}
      - POSTGRES_DB=${ZABBIX_DB_NAME}
      - ZBX_SERVER_HOST=zabbix_server
      - ZBX_SERVER_PORT=10051
      - PHP_TZ=${TZ}
      - ZBX_SERVER_NAME=${ZABBIX_SERVER_NAME}
    depends_on:
      zabbix_server:
        condition: service_started
    ports:
      - "${ZABBIX_PORT}:8080"
    networks:
      - zabbix_network
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_LABEL_ENABLE}"

networks:
  zabbix_network:
    name: zabbix_network
    driver: bridge

