services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    env_file:
      - .env

    # Ports : UI HTTP + tunnel agent
    ports:
      - "${PORTAINER_UI_PORT}:9000"
      - "${PORTAINER_AGENT_TUNNEL_PORT}:8000"

    # Volumes : données et socket Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_BASE_PATH}/data:/data

    # Réseau interne dédié
    networks:
      - portainer_network
    labels:
      - "com.centurylinklabs.watchtower.enable=${PORTAINER_WATCHTOWER_LABEL_ENABLE}"

    # Variables d’environnement optionnelles
    environment:
      - TZ=${PORTAINER_TZ}
      - LOG_LEVEL=${PORTAINER_LOG_LEVEL}

volumes:

networks:
  portainer_network:
    name: portainer_network
    driver: bridge