services:
  semaphore_database:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_USER: ${SEMAPHORE_DB_USER}
      MYSQL_PASSWORD: ${SEMAPHORE_DB_PASS}
      MYSQL_DATABASE: ${SEMAPHORE_DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ${SEMAPHORE_BASE_PATH}/mysql:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - semaphore_network

  semaphore_ui:
    image: semaphoreui/semaphore:v2.16.35
    restart: unless-stopped
    ports:
      - "${SEMAPHORE_UI_PORT}:3000"
    depends_on:
      - semaphore_database
    env_file:
      - .env
    environment:
      SEMAPHORE_DB_DIALECT: ${SEMAPHORE_DB_DIALECT}
      SEMAPHORE_DB_HOST: ${SEMAPHORE_DB_HOST}
      ANSIBLE_HOST_KEY_CHECKING: ${SEMAPHORE_ANSIBLE_HOST_KEY_CHECKING}
    volumes:
      - ${SEMAPHORE_BASE_PATH}/data:/var/lib/semaphore
      - ${SEMAPHORE_BASE_PATH}/config:/etc/semaphore
      - ${SEMAPHORE_BASE_PATH}/tmp:/tmp/semaphore
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - semaphore_network
      
networks:
  semaphore_network:
    driver: bridge