services:
  semaphore_database:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_USER: ${SEMAPHORE_DB_USER}
      MYSQL_PASSWORD: ${SEMAPHORE_DB_PASS}
      MYSQL_DATABASE: ${SEMAPHORE_DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - semaphore_mysql:/var/lib/mysql
    networks:
      - semaphore_network

  semaphore_ui:
    image: semaphoreui/semaphore:v2.16.35
    ports:
      - "3001:3000"
    depends_on:
      - semaphore_database
    env_file:
      - .env
    environment:
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB_HOST: semaphore_database
      ANSIBLE_HOST_KEY_CHECKING: "False"
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore
    networks:
      - semaphore_network

volumes:
  semaphore_data:
  semaphore_config:
  semaphore_tmp:
  semaphore_mysql:

networks:
  semaphore_network:
    driver: bridge